Reference type nima?
azam-amonov/CSharp-Interview-Questions-Uzbek pull request #60
Opened 2024-02-11 08:40 UTC by Mirzohid-Mominov

2024-02-14 19:28 UTC, azam-amonov requested changes
- Javoblar mavhum bo'lmasin
- Tahrirchidan foydlan
- Har bir javob uchun Resource keltirish kerak!

2024-02-14 19:28 UTC, azam-amonov commented on General-Questions/GQ-N-01.md
> +Reference type bu - Reference tipdagi bitta o'zgaruvchining qiymati qayerda saqlangan
Reference type-bu deb boshlash kerak emas!

2024-02-14 19:28 UTC, azam-amonov commented on General-Questions/GQ-N-01.md
> +C# da shuningdek built-in reference type lar ham mavjud: dynamic, object va string.
Keltirilgan misollar tushunarli emas!

2024-02-14 19:28 UTC, azam-amonov commented on General-Questions/GQ-N-01.md
> +
Javobning oxirida Resource bo'lsin!

2024-02-14 19:28 UTC, azam-amonov commented on General-Questions/GQ-N-02.md
> + Value type bu - Bitta o'zgaruvchi deb oladigan bo'lsak shu o'zgaruvchining qiymatini to'g'ridan to'g'ri
Birdan javob berish boshlanishi kerak!

2024-02-14 19:28 UTC, azam-amonov commented on General-Questions/GQ-N-02.md
> +
Yuqoridagi xatolik

2024-02-14 19:28 UTC, azam-amonov commented on General-Questions/GQ-N-03.md
> +
nima emas! Qanday

2024-02-14 19:29 UTC, azam-amonov commented
- Qaysi issular bo'yicha ishlayotganingni kirit!

2024-02-15 08:55 UTC, Mirzohid-Mominov commented
uzi shunaqa deb yozilgan ekan ingliz tilida men ham qoldan kelgancha
tug'irlab tarjima qildim


чт, 15 февр. 2024 г. в 00:30, azam-amonov ***@***.***>:

>
>    - Qaysi issular bo'yicha ishlayotganingni kirit!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/azam-amonov/CSharp-Interview-Questions-Uzbek/pull/60#issuecomment-1944459798>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBYW4CYQBFH4VKV7AJRP5JLYTUGEHAVCNFSM6AAAAABDDL2NKOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNBUGQ2TSNZZHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-02-20 10:13 UTC, merged